####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################
Module: opm-models
Version: 2021.10-pre
Codename: Honey Bunny
Description: OPM's numerical framework for flow and transport in porous media
Url: http://opm-project.org
MaintainerName: The Open Porous Media Project
Maintainer: opm@opm-project.org
Depends: dune-grid (>= 2.6) dune-istl  (>= 2.6) opm-material
Suggests: dune-localfunctions (>= 2.6) dune-fem  (>= 2.6) dune-alugrid (>= 2.6)
